apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-frontend
  name: nginx-frontend
  namespace: default
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-nrfj4
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  restartPolicy: Always
  volumes:
  - name: default-token-nrfj4
    secret:
      defaultMode: 420
      secretName: default-token-nrfj4
